version: 1.0.0

services:
  backend-api:
    build: ./backend-api
    environment:
      - 'APP_PORT=8080'
      - 'APP_HOST=dev'
    ports:
      - '8000:8000'
    volumes:
      - './backend-api:/app'

  backend-datagen:
    build: ./backend-datagen
    environment:
      - 'APP_PORT=8080'
      - 'APP_HOST=dev'
    ports:
      - '8001:8001'
    volumes:
      - './backend-datagen:/app'
    links:
      - backend-api
  



