version: 1.0.0

services:
  backend-api:
    build: ./backend-api
    ports:
      - '8000:8000'
    volumes:
      - './backend-api:/app'

  backend-datagen:
    build: ./backend-datagen
    volumes:
      - './backend-datagen:/app'
    links:
      - backend-api
  



