services:
  api:
    build:
      context: .
      target: dev-envs
    container_name: backend-api
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no"
